today : [today, tdy, now]
tomorrow : [tomorow, tomorrow, tommorrow, tommorow, tmr]
yesterday : [yesterday, yest, ye]
weekdays:
  monday : [monday, mon]
  tuesday : [tuesday, tue]
  wednesday : [wednesday, wed]
  thursday : [thursday, thu]
  friday : [friday, fri]
  saturday : [saturday, sat, weekend]
  sunday : [sunday, sun]
after : [after, from]
before : [before]
ago : [ago]
day : [day, days]
week : [week, weeks]
fortnight : [fortnight, fortnights]
month: [month, months]
year: [year, years]
next: [next, following]
last: [previous, last]
